### ISSUE TITLE
clarity of instructions in readme

### ISSUE THREAD

**Issue by jsms90** [shiryz/pg-workshop#25]
### Getting started
Students have expressed confusion before whenever there is existing code in a workshop but they aren't walked through what that code is doing.

+ [x] Set the scene by explaining what our app does (before [the instructions to clone and `npm install` & `npm run dev`](https://github.com/pbywater/pg-workshop/#getting-started))
+ [x] After they've had a chance to see it in the browser once, give students explicit instruct to change something with the current code, so they see exactly what already exists:
1. Add your own name and location within `handlers/static.js`
2. Refresh the page & check the results  

Note: if you have asked students to `npm run dev`, nodemon should handle the update automatically, so students shouldn't have to manually restart the server before refreshing.

### Task 1
+ [x] Give high-level explanation of the problem:  
We are currently hard-coding the data in to the application (`static.js`) because we don't have a database.  
Now we want students to _replace_ `static.js` with an actual database.
+ [x] Change ["Setting up the database"](https://github.com/pbywater/pg-workshop/#setting-up-the-database) to "Task 1"
+ [x] Turn bullet points into numbered steps
+ [ ] Add [table creation](https://github.com/pbywater/pg-workshop/#task-1) to the end of these steps
    > Create a table called 'users' with three columns: 'id', 'name' and 'location' and add a couple of rows of dummy data. Hint: don't hard code the ids
+ [ ] Final step is to connect this database to "Write a `db_connection.js` file" to the end of these

### Task 2
The original [Task 1](https://github.com/foundersandcoders/pg-workshop#task-1) is good, but
+ [x] could be broken down into more specific steps

> In src/router.js you'll find a function that deals with calls to the /users endpoint. The data is currently coming from the static.js file.
> Change the handler so that the response data comes from the users table in your database instead of from static.js.
> 1. Inside `queries/getUsers.js`, write a SQL query that pulls the necessary data from your database
> 2. Change the `/users` handler in `router.js` (aka `handlers.js`) to call the `getUsers` query

+ [x] should probably point students to the existence of [this line](https://github.com/foundersandcoders/pg-workshop/blob/master/src/handler.js#L6) and explain what it's doing, since they haven't seen this in prior workshops & are likely not to notice it since it's been pre-written

### Task 3
+ [x] Change description of the task from [developer-centric (what kind of query we're writing)](https://github.com/pbywater/pg-workshop#task-2) to user-centric (why we would write that query)
+ [x] Point students to the inline HTML attribute `action="create-user"` as the reason for having to alter the `create-user` handler! (Not everyone is necessarily familiar with this.)
+ [x] Explain what happens when submit button is clicked & what the payload of a form looks like

Right now, the only way to add users to our database, is manually. Only a developer can add users to the database, either through psql in the command line, or by adding `.sql` files to this repo.

But we want to make this accessible via our website, so that people can add users to the database themselves.

1. Uncomment-out the existing form in `index.html`
1. Refresh your browser and make sure you see this

Notice the combination of [`type="submit"` on the button element](https://github.com/foundersandcoders/pg-workshop/blob/master/public/index.html#L19), and the [action attribute on the form](https://github.com/foundersandcoders/pg-workshop/blob/master/public/index.html#L16) (`action="create-user"`). This means that every time the submit button is clicked, we are sending a request to the `/create-user` endpoint on our server, with the contents of the form as the payload:
```js
{
  name: // value of input field goes here,
  location: // value of input field goes here
}
```

1. Add a new endpoint to `router.js` (`/create-user`)
1. Create a handler function for this new endpoint create-user, which uses the data from your form to `INSERT` a new row into your users table
1. Give the users of your website some helpful feedback, so they know that their data has been successfully dealt with.

### Task 4
Style it up! Try and get the design looking as close as possible to the below before adding any new features.

**Comment by pbywater** [comment]
@jsms90 Hopefully this reads better now!
